name = "vortecsmaster/justvalidators"
version = "0.2.1"
license = "Apache-2.0"
description = "Aiken contracts for project 'vortecsmaster/justvalidators'"

[repository]
user = "vortecsmaster"
project = "justvalidators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2a6df1220e0d180eb36cfe4e4265a2d47c5b83cb"
source = "github"
