name = "vortecsmaster/justvalidators"
version = "0.2.1"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'vortecsmaster/justvalidators'"

[repository]
user = "vortecsmaster"
project = "justvalidators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.1.0"
source = "github"
